repos:
  - repo: local
    hooks:
      - id: black-fix
        name: Black fix
        entry: bash -c 'pipenv run black . --skip-string-normalization --line-length 90; git add -u'
        language: system
        pass_filenames: false
        require_serial: true
        fail_fast: false

      - id: isort-fix
        name: Isort fix
        entry: bash -c 'pipenv run isort --profile black .; git add -u'
        language: system
        pass_filenames: false
        require_serial: true
        fail_fast: false

      - id: pylint
        name: Pylint check
        entry: pipenv run pylint . -d C0411,C0412,C0301,C0114,C0115,R0903,E0401,W0707,W0511,R1705,C0103,R0913,R0902,R0801,R0914,W0105,E0611,E1101,R0917,R0401 -j 0 --ignore tests
        language: system
        pass_filenames: false

      - id: flake8
        name: Flake8 check
        entry: pipenv run flake8 --extend-ignore E501,F401,W291 . --exclude "tests/*"
        language: system
        pass_filenames: false

      - id: bandit-low
        name: Bandit high check
        entry: pipenv run bandit -r . -q -x '*/test_*.py' -l
        language: system
        pass_filenames: false

      - id: bandit-mid
        name: Bandit mid check
        entry: pipenv run bandit -r . -q -x '*/test_*.py' -ll
        language: system
        pass_filenames: false

      - id: bandit-high
        name: Bandit low check
        entry: pipenv run bandit -r . -q -x '*/test_*.py' -lll
        language: system
        pass_filenames: false

      - id: black-check
        name: Black check
        entry: pipenv run black . --skip-string-normalization --line-length 90 --check
        language: system
        pass_filenames: false

      - id: isort-check
        name: Isort check
        entry: pipenv run isort -c --profile black .
        language: system
        pass_filenames: false
